import { directusApi } from '@/shared/api'; // Ensure the base Directus API setup is correct.
import { envHelper } from '@/shared/const/envHelper';
import { createDirectus, rest, readItems } from '@directus/sdk';

const directusBaseUrl = envHelper.directusHost;
const client = createDirectus(directusBaseUrl).with(rest());

/**
 * API service for interacting with the Directus backend to fetch news and news categories.
 *
 * This service leverages the Directus SDK to query news articles and their related entities such as
 * categories, media, and translations. It also fetches news categories with their translations and
 * associated images. The service is integrated with Redux Toolkit Query for caching and state management.
 *
 * @service newsApi
 */
export const newsApi = directusApi.injectEndpoints({
    endpoints: (builder) => ({
        /**
         * Fetches the list of published news items along with their associated data.
         *
         * The query includes news content, related category data, translation information, and images (e.g.,
         * titlePicture, extra pictures). The filter ensures that only news items with a status of 'published'
         * are retrieved.
         *
         * @query
         * @returns {Promise<Object>} The data containing the fetched news items.
         * @property {Array} data - An array of news items with their associated details.
         */
        getNews: builder.query({
            queryFn: async (_arg: void) => {
                const newsItems = await client.request(
                    readItems('news', {
                        fields: [
                            '*',
                            'category.*',
                            'titlePicture.*',
                            'extrapicture.*',
                            'extraPicture2.*',
                            'extraPicture3.*',
                            'extraPicture4.*',
                            'category.translations.*',
                            'translations.*',
                        ],
                        deep: {
                            category: { translations: true },
                            translations: true,
                        },
                        filter: {
                            status: { _eq: 'published' },
                        },
                    }),
                );
                return { data: newsItems };
            },
        }),

        /**
         * Fetches a list of news categories, including their images and translations.
         *
         * The query returns the available categories, each with its associated images and translation data.
         *
         * @query
         * @returns {Promise<Object>} The data containing the fetched news categories.
         * @property {Array} data - An array of news categories with their images and translations.
         */
        getNewsCategories: builder.query({
            queryFn: async (_arg: void) => {
                const newsCategories = await client.request(
                    readItems('news_category', {
                        fields: ['*', 'category_image.*', 'translations.*'],
                        deep: { translations: true },
                    }),
                );
                return { data: newsCategories };
            },
        }),
    }),
});

/**
 * Custom hooks generated by Redux Toolkit Query for fetching news and categories.
 *
 * These hooks are used within components to trigger the respective queries and access their results
 * including loading state, data, and errors.
 *
 * @hook {useGetNewsQuery} A hook to fetch the news articles.
 * @hook {useGetNewsCategoriesQuery} A hook to fetch the news categories.
 */
export const { useGetNewsQuery, useGetNewsCategoriesQuery } = newsApi;
