#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Navigate to the project directory
cd frontend-next-migration

# Run the sort-imports script with the --git-changes flag
npx ts-node altzone-cli/sortImports/processFiles.ts --git-changes

# Run lint-staged to check only modified files
npx lint-staged
