name: Check if PR linked to an issue
on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR body for issue reference
        shell: bash
        run: |
          PR_BODY="${{ github.event.pull_request.body }}"

          matches=$(printf '%s\n' "$PR_BODY" | grep -oiE '(Fixes|Resolves|Closes) #[0-9]+' | wc -l)

          if [ "$matches" -lt 1 ]; then
            echo "Please link this PR to an issue (e.g. 'Closes #123')"
            echo "See: https://github.com/Alt-Org/Altzone-WebPages/wiki/4.-Pull-Request#description"
            exit 1
          else
            echo "Issue reference found"
          fi
